config/routes.rb
Rails.application.routes.draw do
  
  
  resources :users
  resources :posts do
    resources :comments
  end
  
  get 'login' => 'sessions#new'
  post 'login' => 'posts#index'
  delete 'logout' => 'sessions#destroy'
  
  root "users#index"
  # root 'posts#index'
  post 'posts/comment_create/:post_id' => 'posts#comment_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    mount_uploader :image, ImageUploader
    validates :title, presence: true, length: {minimum: 1}
    validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255},
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end
    
    private
        def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    protect_from_forgery with: :null_session
    
    def index 
        @posts = Post.all  #첫 화면->picture list
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)  #new.html.erb에서 정보를 받아옴
    
        if @post.save  #db에 저장
            redirect_to @post  #show.html.erb로 이동
        else
            render 'new'
        end
    end
    
    def show
        @post = Post.find(params[:id])  #해당 post의 id로부터 post 객체를 찾아 보여줌
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
          redirect_to @post
        else
          render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
      
        redirect_to posts_path
    end
    
    private
        def post_params
            params.require(:post).permit(:title, :information, :image)  #post의 변수들을 저장
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to :root
    else
      flash.now[:alert] = "이메일 또는 패스워드가 잘못되었습니다."
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to :root
  end

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def index
    @users = User.all
  end
  
  def create
    User.create(name: params[:name],
                email: params[:email],
                password: params[:password],
                password_confirmation: params[:password_confirmation])
    redirect_to :root
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def user_signed_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
    end
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGallary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %><br>
    <% if user_signed_in? %>
      <%= link_to '로그아웃', logout_path, method: 'delete' %>
    <% else %>
      <%= link_to '로그인', login_path %>
      <%= link_to '회원가입', new_user_path %>
    <% end %>
  <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Picture Information</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    Picture
    <% f.label :image %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :information %><br>
    <%= f.text_area :information %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Picture List</h1>

<%= link_to 'Add New Picture', new_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.information %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Picture</h1>
<%= form_for :post, url:posts_path do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <% f.label :image %>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :information %><br>
    <%= f.text_area :information %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', posts_path %> 

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Picture:</strong><br>
  <img src="<%= @post.image.url %>">
</p>

<p>
  <strong>Information:</strong>
  <%= @post.information%>
</p>

<strong>(Commenter) Comment:</strong><br>
<% @post.comments.each do |comment| %>
  <p>
    (<%= comment.commenter %>) &nbsp
    <%= comment.body %>
  </p>
<% end %>

<h3>Add a comment:</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %>

app/views/users/index.html.erb
<h1>회원 가입 공부중입니다.</h1>
<% @users.each do |u| %>
    <li><%=u.name%></li>
<% end %>
<% if user_signed_in? %>
    로그인한 유저 :
    <%= current_user.email %>
<% end %>

app/views/users/new.html.erb
<h1>회원 가입</h1>
<%= form_tag users_path do %>
    이름
    <input type="text" name="name"><br>
    이메일
    <input type="email" name="email"><br>
    패스워드
    <input type="password" name="password"><br>
    패스워드 확인
    <input type="password" name="password_confirmation"><br>
    <input type="submit" value="회원 가입">
<% end %>